@startuml US042_CD
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class ImportBulkWeatherDataUI {
}

class ImportBulkWeatherDataController {
    + ImportBulkWeatherDataController()
    + previewImport(filePath) : List<WeatherDataDTO>
    + confirmImport(weatherDataDTOList) : int
}

class WeatherDataImporterFactory {
    + getImporter(filePath) : WeatherDataImporter
}

interface WeatherDataImporter {
    + readWeatherData(filePath) : List<WeatherDataDTO>
}

class CsvWeatherDataImporter {
    + readWeatherData(filePath) : List<WeatherDataDTO>
}

class WeatherDataDTO {
    + areaCode : String
    + day : LocalDate
    + startTime : LocalTime
    + endTime : LocalTime
    + latStart : double
    + lonStart : double
    + latEnd : double
    + lonEnd : double
    + altitudeMin : int
    + altitudeMax : int
    + windDirection : double
    + windSpeed : double
}

class WeatherData {
    - weatherDataID : WeatherDataID
    - airControlAreaCode : AirControlAreaCode
    - day : LocalDate
    - startTime : LocalTime
    - endTime : LocalTime
    - boundingBox : BoundingBox
    - altitudeMin : int
    - altitudeMax : int
    - windDirection : double
    - windSpeed : double

    + WeatherData(areaCode, day, startTime, endTime,\nboundingBox, altitudeMin, altitudeMax,\nwindDirection, windSpeed)
}

class WeatherDataID {
    - number : String
}

class BoundingBox {
    + BoundingBox(start, end)
}

class Coordinates {
    - latitude : double
    - longitude : double
}

class AirControlAreaCode {
    - code : String
}

class WeatherDataRepository {
    + save(weatherData)
    + findByAreaAndDate(areaCode, date) : List<WeatherData>
}

class Repositories {
    - Repositories()
    + {static} getInstance()
    + getWeatherDataRepository()
}

ImportBulkWeatherDataUI .> ImportBulkWeatherDataController

ImportBulkWeatherDataController .> Repositories
ImportBulkWeatherDataController ..> WeatherDataRepository
ImportBulkWeatherDataController ..> WeatherDataImporterFactory
ImportBulkWeatherDataController ..> WeatherDataImporter
ImportBulkWeatherDataController ..> WeatherDataDTO
ImportBulkWeatherDataController ..> WeatherData

WeatherDataImporterFactory ..> WeatherDataImporter
WeatherDataImporter <|.. CsvWeatherDataImporter
CsvWeatherDataImporter ..> WeatherDataDTO

Repositories -> "1" Repositories : instance
Repositories --> "1" WeatherDataRepository : weatherDataRepository

WeatherDataRepository --> "*" WeatherData : weatherDataList

WeatherData *-- "1" WeatherDataID : weatherDataID
WeatherData --> "1" AirControlAreaCode : airControlAreaCode
WeatherData --> "1" BoundingBox : boundingBox

BoundingBox --> "1" Coordinates : start
BoundingBox --> "1" Coordinates : end

@enduml