@startuml
skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam shadowing false

skinparam class {
    BackgroundColor<<Aggregate Root>> #E3F2FD
    BorderColor<<Aggregate Root>> #1565C0
    FontColor<<Aggregate Root>> #1565C0
    HeaderBackgroundColor<<Aggregate Root>> #BBDEFB

    BackgroundColor<<Entity>> #FFF8E1
    BorderColor<<Entity>> #F57F17
    FontColor<<Entity>> #F57F17
    HeaderBackgroundColor<<Entity>> #FFE082

    BackgroundColor<<Value Object>> #F1F8E9
    BorderColor<<Value Object>> #558B2F
    FontColor<<Value Object>> #558B2F
    HeaderBackgroundColor<<Value Object>> #DCEDC8
}

skinparam package {
    BackgroundColor #FAFAFA
    BorderColor #BDBDBD
    BorderStyle dashed
    FontSize 14
}


skinparam ArrowColor #444441

package "EngineModel Aggregate" <<Frame>> {

    class EngineModel <<Aggregate Root>> {
        - name : String
        - engineModelID : EngineModelID
        - type : EngineType
        - power : double
        - fuel : FuelType
        - tsfc : double
        - makerID : MakerID
    }


    class EngineModelID <<Value Object>>{
        - number : String
    }

    enum FuelType <<Value Object>> {
        JET_A1
        AVGAS
        ELECTRIC
        HYBRID
    }

    enum EngineType <<Value Object>> {
        TURBOPROP
        TURBOFAN
        TURBOJET
        RAMJET
        ELECTRIC_PROPELLER
    }

    EngineModel --> EngineType
    EngineModel --> FuelType
    EngineModel *-- EngineModelID


}
@enduml