@startuml
skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam shadowing false

skinparam class {
    BackgroundColor<<Aggregate Root>> #E3F2FD
    BorderColor<<Aggregate Root>> #1565C0
    FontColor<<Aggregate Root>> #1565C0
    HeaderBackgroundColor<<Aggregate Root>> #BBDEFB

    BackgroundColor<<Entity>> #FFF8E1
    BorderColor<<Entity>> #F57F17
    FontColor<<Entity>> #F57F17
    HeaderBackgroundColor<<Entity>> #FFE082

    BackgroundColor<<Value Object>> #F1F8E9
    BorderColor<<Value Object>> #558B2F
    FontColor<<Value Object>> #558B2F
    HeaderBackgroundColor<<Value Object>> #DCEDC8
}

skinparam package {
    BackgroundColor #FAFAFA
    BorderColor #BDBDBD
    BorderStyle dashed
    FontSize 14
}


skinparam ArrowColor #444441

package "FlightSimulation Aggregate" <<Frame>> {

    class FlightSimulation <<Aggregate Root>> {
        - flightSimulationID : FlightSimulationID
        - airControlAreaCode : AirControlAreaCode
        - status : SimulationStatus
        - startedAt : LocalDateTime
        - finishedAt : LocalDateTime
    }

    class FlightSimulationID <<Value Object>> {
        - number : String
    }

    class FlightExecution <<Entity>> {
        - flightExecutionID : FlightExecutionID
        - flightPlanID : FlightPlanID
        - status : FlightExecutionStatus
        - fuelConsumed : double
    }

    class FlightExecutionID <<Value Object>> {
        - number : String
    }

    class SafetyViolationEvent <<Value Object>> {
        - timestamp : LocalDateTime
        - coordinates : Coordinates
        - involvedFlightExecutionIDs : Set<FlightExecutionID>
    }

    class SimulationReport <<Value Object>> {
        - totalFlights : int
        - globalResult : SimulationGlobalResult
        - safetyViolations : List<SafetyViolationEvent>
        + flightExecutionSummaries : List<FlightExecutionID>
    }

    enum SimulationStatus <<Value Object>> {
        PENDING
        RUNNING
        COMPLETED
        FAILED
    }

    enum FlightExecutionStatus <<Value Object>> {
        RUNNING
        COMPLETED
        TERMINATED
        FAILED
    }

    enum SimulationGlobalResult <<Value Object>> {
        PASSED
        FAILED
    }

    class Coordinates <<Value Object>> {
        - latitude : double
        - longitude : double
    }

    SafetyViolationEvent *-- Coordinates


    FlightSimulation *-- "1..*" FlightExecution
    FlightSimulation *-- SimulationReport
    SimulationReport *-- "0..*" SafetyViolationEvent
    FlightSimulation --> SimulationStatus
    FlightExecution --> FlightExecutionStatus
    SimulationReport --> SimulationGlobalResult
    FlightSimulation *-- FlightSimulationID
    FlightExecution *-- FlightExecutionID
}
@enduml