@startuml SSD_us42

title US42 - Import bulk weather data

actor "Weather person" as ACTOR
participant ":System" as SYSTEM

activate ACTOR

ACTOR -> SYSTEM : wants to import bulk weather data from a file
activate SYSTEM

SYSTEM --> ACTOR : requests file path
deactivate SYSTEM

ACTOR -> SYSTEM : provides file path
activate SYSTEM

SYSTEM --> ACTOR : shows all data and requests confirmation
deactivate SYSTEM

ACTOR -> SYSTEM : confirms data
activate SYSTEM

SYSTEM --> ACTOR : shows operation success
deactivate SYSTEM

deactivate ACTOR

@enduml