@startuml AISafe_CompleteDomainModel

skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam shadowing false

skinparam class {
    BackgroundColor<<Aggregate Root>> #E3F2FD
    BorderColor<<Aggregate Root>> #1565C0
    FontColor<<Aggregate Root>> #1565C0
    HeaderBackgroundColor<<Aggregate Root>> #BBDEFB

    BackgroundColor<<Entity>> #FFF8E1
    BorderColor<<Entity>> #F57F17
    FontColor<<Entity>> #F57F17
    HeaderBackgroundColor<<Entity>> #FFE082

    BackgroundColor<<Value Object>> #F1F8E9
    BorderColor<<Value Object>> #558B2F
    FontColor<<Value Object>> #558B2F
    HeaderBackgroundColor<<Value Object>> #DCEDC8
}

skinparam package {
    BackgroundColor #FAFAFA
    BorderColor #BDBDBD
    BorderStyle dashed
    FontSize 14
}


skinparam ArrowColor #444441

package "Shared Kernel" <<Frame>>{

        class Coordinates <<Value Object>> {
            - latitude : double
            - longitude : double
        }


        class Country <<Value Object>> {
            - isoCode : IsoCode
            - name : String
        }

        class IsoCode <<Value Object>>{
            - code : String
        }

        class IataCode <<Value Object>>{
            - code : String
        }

        class IcaoCode <<Value Object>>{
             - code : String
        }

}

package "User Aggregate" <<Frame>> {

    class User <<Aggregate Root>> {
        - email : Email
        - userID : UserID
        - name : String
	    - phoneNumber: PhoneNumber
        - roles : Set<Role>
        - securityClearance : SecurityClearance
        - latestSkillsAssessment : SkillsAssessment
        - status : UserStatus
    }

    class Email <<Value Object>>{
        - address : String
    }

    class UserID <<Value Object>>{
        - number: String
    }

    enum UserStatus <<Value Object>> {
        ENABLED
        DISABLED
    }

     class PhoneNumber <<Value Object>> {
         - countryCode : int
         - number : String
     }

     class SecurityClearance <<Value Object>> {
        - level : ClearanceLevel
        - expiresAt : LocalDate

      }

    class SkillsAssessment <<Value Object>> {
        - date : LocalDate
        - result : AssessmentResult
    }

    enum Role <<Value Object>> {
        ADMIN
        BACKOFFICE_OPERATOR
        AIR_TRANSPORT_COMPANY_COLLABORATOR
        PILOT
        FLIGHT_CONTROL_OPERATOR
        WEATHER_PERSON
    }

    enum ClearanceLevel <<Value Object>> {
        LOW
        MEDIUM
        HIGH
        CRITICAL
    }

    enum AssessmentResult <<Value Object>> {
        PASSED
        FAILED
        CONDITIONAL
    }

}

package "Maker Aggregate" <<Frame>> {

    class Maker <<Aggregate Root>> {
        - name : String
        - makerID : MakerID
        - country : Country
        - makerType: Set<MakerType>
    }

    class MakerID <<Value Object>>{
        - number : String
    }

    enum MakerType <<Value Object>>{
        ENGINE
        AIRCRAFT
    }
}

package "AirControlArea Aggregate" <<Frame>> {

    class AirControlArea <<Aggregate Root>> {
        - code : AirControlAreaCode
        - geographicBounds : GeographicBoundary
    }

    class AirControlAreaCode <<Value Object>>{
        - code : String
    }

    class GeographicBoundary <<Value Object>> {
        - coordinates : List<Coordinates>
    }
}

package "Airport Aggregate" <<Frame>> {

    class Airport <<Aggregate Root>> {
        - name : String
        - town : String
        - country : Country
        - airControlAreaCode : AirControlAreaCode
        - iataCode : IataCode
        - icaoCode : IcaoCode
        - coordinates: Coordinates
        - elevation: double
    }
}


package "EngineModel Aggregate" <<Frame>> {

    class EngineModel <<Aggregate Root>> {
        - name : String
        - engineModelID : EngineModelID
        - type : EngineType
        - power : double
        - fuel : FuelType
        - tsfc : double
        - makerID : MakerID
    }


    class EngineModelID <<Value Object>>{
        - number : String
    }

    enum FuelType <<Value Object>> {
        JET_A1
        AVGAS
        ELECTRIC
        HYBRID
    }

    enum EngineType <<Value Object>> {
        TURBOPROP
        TURBOFAN
        TURBOJET
        RAMJET
        ELECTRIC_PROPELLER
    }

}

package "AircraftModel Aggregate" <<Frame>> {

    class AircraftModel <<Aggregate Root>> {
        - modelID : AircraftModelID
        - name : String
        - type : AircraftType
        - emptyWeight : double
        - mtow : double
        - mzfw : double
        - maxFuelCapacity : double
        - serviceCeiling : double
        - cruiseSpeed : double
        - wingArea : double
        - dragCoefficient : double
        - liftCoefficient : double
        - maximumRange : double
        - maxPassengerCapacity : int
        - certifiedEngineModelIDs : Set<EngineModelID>
        - engineNumber : int
        - makerID : MakerID
    }

    class AircraftModelID <<Value Object>>{
        - number : String
    }

    enum AircraftType <<Value Object>> {
        PASSENGER
        CARGO
        MIXED
    }

}

package "AirTransportCompany Aggregate" <<Frame>> {

    class AirTransportCompany <<Aggregate Root>> {
        - name : String
        - iataCode : IataCode
        - icaoCode : IcaoCode
    }

    enum AirTransportCompanyState <<Value Object>>{
        ACTIVE
        INACTIVE
    }
}

package "Aircraft Aggregate" <<Frame>> {

    class Aircraft <<Aggregate Root>> {
        - registration : AircraftRegistration
        - country : Country
        - operationalStatus : OperationalStatus
        - numCrewElements : int
        - cabinConfiguration : CabinConfiguration
        - aircraftModelID : AircraftModelID
        - airTransportCompanyIataCode  : IataCode

    }

    class AircraftRegistration <<Value Object>>{
        - registration : String
    }

    class CabinConfiguration <<Value Object>> {
        - seatsPerClass : Map<SeatClass, Integer>
    }

    enum SeatClass <<Value Object>> {
        ECONOMY
        BUSINESS
        FIRST
    }

    enum OperationalStatus <<Value Object>> {
        ACTIVE
        DECOMMISSIONED
    }
}



package "FlightRoute Aggregate" <<Frame>> {

    class FlightRoute <<Aggregate Root>> {
        - routeCode : RouteCode
        - status : RouteStatus
        - departureAirportIataCode : IataCode
        - arrivalAirportIataCode : IataCode
        - airTransportCompanyIataCode : IataCode
    }


    class RouteCode <<Value Object>> {
        - value : String
    }

    enum RouteStatus <<Value Object>> {
        ACTIVE
        INACTIVE
    }
}

package "FlightSimulation Aggregate" <<Frame>> {

    class FlightSimulation <<Aggregate Root>> {
        - flightSimulationID : FlightSimulationID
        - airControlAreaCode : AirControlAreaCode
        - status : SimulationStatus
        - startedAt : LocalDateTime
        - finishedAt : LocalDateTime
    }

    class FlightSimulationID <<Value Object>> {
        - number : String
    }

    class FlightExecution <<Entity>> {
        - flightExecutionID : FlightExecutionID
        - status : FlightExecutionStatus
        - fuelConsumed : double
    }

    class FlightExecutionID <<Value Object>> {
        - number : String
    }

    class SafetyViolationEvent <<Value Object>> {
        - timestamp : LocalDateTime
        - coordinates : Coordinates
        - involvedFlightExecutionIDs : Set<FlightExecutionID>
    }

    class SimulationReport <<Value Object>> {
        - totalFlights : int
        - globalResult : SimulationGlobalResult
        - safetyViolations : List<SafetyViolationEvent>
    }

    enum SimulationStatus <<Value Object>> {
        PENDING
        RUNNING
        COMPLETED
        FAILED
    }

    enum FlightExecutionStatus <<Value Object>> {
        RUNNING
        COMPLETED
        TERMINATED
        FAILED
    }

    enum SimulationGlobalResult <<Value Object>> {
        PASSED
        FAILED
    }
}

package "Weather Aggregate" <<Frame>> {
    class WeatherData <<Aggregate Root>> {
        - collectedAt : LocalDateTime
        - coordinates: Coordinates
        - weatherDataID : WeatherDataID
        - windDirection : double
        - windSpeed : double
        - temperature : double
        - airControlAreaCode : AirControlAreaCode
    }

    class WeatherDataID <<Value Object>>{
        - number : String
    }
}

package "Pilot Aggregate" <<Frame>> {

    class Pilot <<Aggregate Root>> {
        - pilotID : PilotID
        - userID : UserID
        - currentCompanyIataCode : IataCode
        - certifications : Set<Certification>
        - status : PilotStatus
    }

    class PilotID <<Value Object>> {
        - number : String
    }

    class Certification <<Value Object>> {
        - aircraftModelID : AircraftModelID
        - pilotAircraftHours : int
        - issuedAt : LocalDate
        - validUntil : LocalDate
    }

    enum PilotStatus <<Value Object>> {
        ACTIVE
        INACTIVE
    }
}

package "ATCC Aggregate" <<Frame>> {

    class ATCC <<Aggregate Root>> {
        - atccID : ATCCID
        - userID : UserID
        - currentCompanyIataCode : IataCode
        - position : String
        - status : ATCCStatus
    }

    class ATCCID <<Value Object>> {
        - number : String
    }

    enum ATCCStatus <<Value Object>> {
        ACTIVE
        DISABLED
    }
}

package "Flight Aggregate" <<Frame>> {

    class Flight <<Aggregate Root>> {
        - flightID : FlightID
        - flightType : FlightType
        - schedule : Schedule
        - routeCode : RouteCode
    }

    class FlightID <<Value Object>>{
        - code : String
    }

    enum FlightType <<Value Object>>{
        REGULAR
        CHARTER
    }

    abstract class Schedule <<Value Object>>{}

    class ScheduleEntry <<Value Object>>{
        - dayOfTheWeek : DayOfWeek
        - departureTime : LocalDateTime
        - arrivalTime : LocalDateTime
    }

    class CharterSchedule <<Value Object>>{
        - departureTime : LocalDateTime
        - arrivalTime : LocalDateTime
    }

    class RegularSchedule <<Value Object>>{
        - entry : ScheduleEntry
    }

    class FlightPlan <<Entity>> {
        - flightPlanID : FlightPlanID
        - status : FlightPlanStatus
        - aircraftRegistration : AircraftRegistration
        - pilotID : PilotID
        - fuelQuantity : FuelQuantity
        - plannedDeparture : LocalDateTime
        - plannedArrival : LocalDateTime
    }

    class FlightPlanID <<Value Object>>{
        - number : String
    }

    class FuelQuantity <<Value Object>> {
        - amount : double
        - unit : FuelUnit

    }

    enum FuelUnit <<Value Object>> {
        KG
        L
    }

    enum FlightPlanStatus <<Value Object>> {
        DRAFT
        VALIDATED
    }


}

FlightSimulation *-- SimulationReport
SimulationReport *-- "0..*" SafetyViolationEvent

Aircraft *-- CabinConfiguration


User *-- PhoneNumber
User *-- SecurityClearance
User *-- SkillsAssessment

Pilot *-- "1..*" Certification

FlightPlan --> Aircraft : aircraftRegistration
FlightPlan --> Pilot : pilotID

FlightSimulation --> AirControlArea : airControlAreaCode

Aircraft --> AircraftModel : aircraftModelID
Aircraft --> AirTransportCompany : airTransportCompanyIataCode

EngineModel --> Maker : makerID

AircraftModel --> Maker : makerID

Airport --> AirControlArea : airControlAreaCode

Pilot --> User : userID
Pilot --> AirTransportCompany : currentCompanyIataCode

ATCC --> User : userID
ATCC --> AirTransportCompany : currentCompanyIataCode

WeatherData --> AirControlArea : airControlAreaCode

FlightRoute --> Airport : departureAirportIataCode
FlightRoute --> Airport : arrivalAirportIataCode
FlightRoute --> AirTransportCompany : airTransportCompanyIataCode

User --> UserStatus
User --> Role
SecurityClearance --> ClearanceLevel
SkillsAssessment --> AssessmentResult

Maker --> MakerType

EngineModel --> EngineType
EngineModel --> FuelType

AircraftModel --> AircraftType

Aircraft --> OperationalStatus
CabinConfiguration --> SeatClass

FlightRoute --> RouteStatus

FlightPlan --> FlightPlanStatus
FuelQuantity --> FuelUnit

FlightSimulation --> SimulationStatus
FlightExecution --> FlightExecutionStatus
SimulationReport --> SimulationGlobalResult

Pilot --> PilotStatus

ATCC --> ATCCStatus

User *-- UserID
User *-- Email

Maker *-- MakerID

AirControlArea *-- AirControlAreaCode
AirControlArea *-- GeographicBoundary


EngineModel *-- EngineModelID

AircraftModel *-- AircraftModelID

Aircraft *-- AircraftRegistration

Flight *-- FlightID
Flight *-- Schedule
Schedule <|-- RegularSchedule
Schedule <|-- CharterSchedule
RegularSchedule *-- "1..*" ScheduleEntry
Flight --> FlightRoute : routeCode
FlightRoute *-- RouteCode

FlightPlan *-- FlightPlanID

FlightSimulation *-- FlightSimulationID
FlightExecution *-- FlightExecutionID

WeatherData *-- WeatherDataID

Pilot *-- PilotID

ATCC *-- ATCCID

AirTransportCompany <|-- AirTransportCompanyState

FlightExecution --* FlightSimulation

FlightSimulation --> Flight

Country *-- IsoCode

FlightPlan *-- FuelQuantity
Flight *-- "1..*" FlightPlan

Flight *-- FlightType

@enduml