@startuml US042_SD
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Weather Person" as WP
participant ":ImportBulkWeatherDataUI" as UI
participant ":ImportBulkWeatherDataController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "weatherDataRepository\n:WeatherDataRepository" as WD_REPO
participant "authorizationService\n:AuthorizationService" as AUTH
participant ":WeatherDataImporterFactory" as FACTORY
participant "importer\n:WeatherDataImporter" as IMPORTER
participant "weatherData\n:WeatherData" as WD

activate WP

    WP -> UI : asks to import bulk weather data
    activate UI
        UI --> CTRL** : create()
        UI --> WP : requests file path
    deactivate UI

    WP -> UI : provides file path(filePath)
    activate UI

        UI -> CTRL : previewImport(filePath)
        activate CTRL

            CTRL -> AUTH : ensureAuthenticatedUserHasAnyOf(WEATHER_PERSON)
            activate AUTH
                AUTH --> CTRL
            deactivate AUTH

            CTRL -> FACTORY : getImporter(filePath)
            activate FACTORY
                FACTORY --> CTRL : importer
            deactivate FACTORY

            CTRL -> IMPORTER : readWeatherData(filePath)
            activate IMPORTER
                IMPORTER --> CTRL : weatherDataDTOList
            deactivate IMPORTER

            CTRL --> UI : weatherDataDTOList
        deactivate CTRL

        UI --> WP : shows data preview and requests confirmation
    deactivate UI

    WP -> UI : confirms data
    activate UI

        UI -> CTRL : confirmImport(weatherDataDTOList)
        activate CTRL

            loop for each weatherDataDTO in weatherDataDTOList

                CTRL --> WD** : create(areaCode, day, startTime, endTime,\nboundingBox, altitudeMin, altitudeMax,\nwindDirection, windSpeed)

                CTRL -> REPOS : getInstance()
                activate REPOS
                    REPOS --> CTRL : repositories
                deactivate REPOS

                CTRL -> REPOS_SINGLETON : getWeatherDataRepository()
                activate REPOS_SINGLETON
                    REPOS_SINGLETON --> CTRL : weatherDataRepository
                deactivate REPOS_SINGLETON

                CTRL -> WD_REPO : save(weatherData)
                activate WD_REPO
                    WD_REPO --> CTRL : weatherData
                deactivate WD_REPO

            end

            CTRL --> UI : importedCount
        deactivate CTRL

        UI --> WP : displays operation success
    deactivate UI

deactivate WP
@enduml