@startuml
skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam shadowing false

skinparam class {
    BackgroundColor<<Aggregate Root>> #E3F2FD
    BorderColor<<Aggregate Root>> #1565C0
    FontColor<<Aggregate Root>> #1565C0
    HeaderBackgroundColor<<Aggregate Root>> #BBDEFB

    BackgroundColor<<Entity>> #FFF8E1
    BorderColor<<Entity>> #F57F17
    FontColor<<Entity>> #F57F17
    HeaderBackgroundColor<<Entity>> #FFE082

    BackgroundColor<<Value Object>> #F1F8E9
    BorderColor<<Value Object>> #558B2F
    FontColor<<Value Object>> #558B2F
    HeaderBackgroundColor<<Value Object>> #DCEDC8
}

skinparam package {
    BackgroundColor #FAFAFA
    BorderColor #BDBDBD
    BorderStyle dashed
    FontSize 14
}


skinparam ArrowColor #444441

package "User Aggregate" <<Frame>> {

    class User <<Aggregate Root>> {
        - email : Email
        - userID : UserID
        - name : String
	    - phoneNumber: PhoneNumber
        - roles : Set<Role>
        - securityClearance : SecurityClearance
        - latestSkillsAssessment : SkillsAssessment
        - status : UserStatus
    }

    class Email <<Value Object>>{
        - address : String
    }

    class UserID <<Value Object>>{
        - number: String
    }

    enum UserStatus <<Value Object>> {
        ENABLED
        DISABLED
    }

     class PhoneNumber <<Value Object>> {
         - countryCode : int
         - number : String
     }

     class SecurityClearance <<Value Object>> {
        - level : ClearanceLevel
        - expiresAt : LocalDate

      }

    class SkillsAssessment <<Value Object>> {
        - date : LocalDate
        - result : AssessmentResult

        + isRecentEnough(onDate: LocalDate) : boolean
    }

    enum Role <<Value Object>> {
        ADMIN
        BACKOFFICE_OPERATOR
        AIR_TRANSPORT_COMPANY_COLLABORATOR
        PILOT
        FLIGHT_CONTROL_OPERATOR
        WEATHER_PERSON
    }

    enum ClearanceLevel <<Value Object>> {
        LOW
        MEDIUM
        HIGH
        CRITICAL
    }

    enum AssessmentResult <<Value Object>> {
        PASSED
        FAILED
        CONDITIONAL
    }


SecurityClearance --> ClearanceLevel
SkillsAssessment --> AssessmentResult
User --> UserStatus
User --> Role
User *-- UserID
User *-- Email
User *-- PhoneNumber
User *-- SecurityClearance
User *-- SkillsAssessment
}
@enduml